from django.urls import path

from .agent_views import AgentPlanRefreshView, AgentPlanView
from .views import (
    AchievementsView,
    ActionStatsView,
    ActionTemplatesView,
    # Sitemap audit
    AgentLogView,
    AiChatView,
    AiRecommendationSummaryView,
    AnalysisRunBySlugView,
    AnalysisRunDetailView,
    AnalysisRunListView,
    AnalysisRunStatusView,
    AnswerGapFaqView,
    ApplyGeoFixesAndReanalyzeView,
    AssignActionView,
    AutoFixApproveView,
    AutoFixPreviewView,
    AutoFixVerifyView,
    # New features
    AutoFixView,
    BacklinkCatalogView,
    BacklinkOrderConfirmPaymentView,
    BacklinkOrderDetailView,
    BacklinkOrderListCreateView,
    BacklinkScheduleView,
    BlogAutomationCalendarView,
    BlogAutomationConfigView,
    BlogAutomationGenerateView,
    BlogAutomationProcessDueView,
    BlogAutomationPublishView,
    BlogAutoPublishAllView,
    BlogComposerGenerateView,
    BlogComposerPostsView,
    BlogComposerPublishView,
    BlogComposerTopicsView,
    BlogComposerUploadImageView,
    BlogGenerateView,
    BlogPostDetailView,
    BlogPublishNetworkView,
    BlogSourcesView,
    BlogTitleIdeasView,
    BrandDomainAuthorityView,
    BulkCreateUserActionView,
    CitationGapsView,
    CitationSourcesView,
    CitationTrendView,
    CompetitorDetailView,
    CompetitorListCreateView,
    CompetitorPromptGenerateView,
    CompetitorPromptListView,
    CompetitorVisibilityMatrixView,
    ContentApplyElementView,
    ContentPageFieldsView,
    # Content optimisation (Cursor-style edit + save)
    ContentPagesView,
    ContentRawFilesListView,
    ContentRawFileUpsertView,
    ContentRewriteElementView,
    ContentSaveView,
    ContentSuggestionDismissView,
    ContentSuggestionsView,
    CrawlerAccessView,
    CrawlerIngestView,
    CrawlerLogsView,
    CrawlEssentialsStatusView,
    CreateUserActionView,
    DomainAnalyticsView,
    DomainRatingFreeView,
    EntityResolutionView,
    ExportPDFView,
    GeneratePromptsView,
    GeoImprovementsView,
    HealthCheckView,
    IndexNowView,
    LatestRunProgressView,
    OnboardingStartView,
    OurBacklinksView,
    OutreachBenchmarkCreateView,
    OutreachBenchmarkDetailView,
    OverviewInsightsView,
    ProjectionView,
    PromptAnswerBlockView,
    PromptBacklinksView,
    PromptCoverageView,
    PromptDeleteView,
    PromptListCreateView,
    PromptOpportunitiesView,
    PromptOpportunityDetailView,
    PromptRankView,
    PromptResultDetailView,
    PromptSchemaView,
    PromptWikipediaDraftView,
    PublicBlogDetailView,
    PublicBlogListView,
    QuickActionView,
    # Schema watchtower
    RankAuditDetailView,
    RankAuditRefreshQueryView,
    # Rank tracker
    RankAuditStartView,
    RankingsView,
    RecheckAllPromptsView,
    RecheckPromptView,
    RunBacklinkFreeView,
    ScheduledAnalysisView,
    SchemaWatchDetailView,
    # Schema watchtower
    SchemaWatchStartView,
    # New features
    ScoreHistoryView,
    ShareOfVoiceCompetitorsView,
    ShareOfVoiceView,
    ShoppingReadinessView,
    ShoppingSyncView,
    SitemapAuditDetailView,
    # Sitemap audit
    SitemapAuditStartView,
    StartAnalysisView,
    SyncActionsView,
    TopSourcesView,
    UpdateUserActionView,
    UserActionListView,
    # Gamification views
    UserGamificationView,
    VerifyActionView,
    VisibilitySeriesView,
    WeeklyTestEmailView,
    WorkerHealthView,
)

app_name = "analyzer"

urlpatterns = [
    path("health/", HealthCheckView.as_view(), name="health-check"),
    path("health/worker/", WorkerHealthView.as_view(), name="worker-health-check"),
    path("tools/domain-rating/", DomainRatingFreeView.as_view(), name="domain-rating-free"),
    path("onboarding-start/", OnboardingStartView.as_view(), name="onboarding-start"),
    path("analyze/", StartAnalysisView.as_view(), name="start-analysis"),
    path("generate-prompts/", GeneratePromptsView.as_view(), name="generate-prompts"),
    path("runs/history/", ScoreHistoryView.as_view(), name="run-history"),
    path("schedule/", ScheduledAnalysisView.as_view(), name="schedule"),
    path("runs/", AnalysisRunListView.as_view(), name="run-list"),
    # Before "runs/<slug>" style routes: a literal segment must not be
    # swallowed by a variable one.
    path("runs/progress/", LatestRunProgressView.as_view(), name="run-progress"),
    path("runs/<int:run_id>/", AnalysisRunDetailView.as_view(), name="run-detail"),
    path("runs/s/<str:slug>/prompts/", PromptListCreateView.as_view(), name="prompt-list-create"),
    # The literal "generate" segment must precede the list route so it is not
    # shadowed by it.
    path(
        "runs/s/<str:slug>/competitor-prompts/generate/",
        CompetitorPromptGenerateView.as_view(),
        name="competitor-prompts-generate",
    ),
    path(
        "runs/s/<str:slug>/competitor-prompts/",
        CompetitorPromptListView.as_view(),
        name="competitor-prompt-list",
    ),
    path(
        "runs/s/<str:slug>/prompts/<int:track_id>/results/<int:result_id>/",
        PromptResultDetailView.as_view(),
        name="prompt-result-detail",
    ),
    path(
        "runs/s/<str:slug>/prompts/<int:track_id>/recheck/",
        RecheckPromptView.as_view(),
        name="prompt-recheck",
    ),
    path(
        "runs/s/<str:slug>/prompts/<int:track_id>/backlinks/",
        PromptBacklinksView.as_view(),
        name="prompt-backlinks",
    ),
    path(
        "runs/s/<str:slug>/prompts/<int:track_id>/opportunities/",
        PromptOpportunitiesView.as_view(),
        name="prompt-opportunities",
    ),
    path(
        "runs/s/<str:slug>/prompts/<int:track_id>/opportunities/<int:opp_id>/",
        PromptOpportunityDetailView.as_view(),
        name="prompt-opportunity-detail",
    ),
    path("runs/s/<str:slug>/prompts/<int:track_id>/", PromptDeleteView.as_view(), name="prompt-delete"),
    path("runs/s/<str:slug>/recheck-all/", RecheckAllPromptsView.as_view(), name="prompt-recheck-all"),
    path("runs/s/<str:slug>/share-of-voice/", ShareOfVoiceView.as_view(), name="share-of-voice"),
    # Dashboard v2 aggregates
    path(
        "runs/s/<str:slug>/visibility-series/",
        VisibilitySeriesView.as_view(),
        name="visibility-series",
    ),
    path("runs/s/<str:slug>/rankings/", RankingsView.as_view(), name="rankings"),
    path(
        "runs/s/<str:slug>/projection/",
        ProjectionView.as_view(),
        name="projection",
    ),
    path(
        "runs/s/<str:slug>/share-of-voice-competitors/",
        ShareOfVoiceCompetitorsView.as_view(),
        name="share-of-voice-competitors",
    ),
    path(
        "runs/s/<str:slug>/competitor-visibility-matrix/",
        CompetitorVisibilityMatrixView.as_view(),
        name="competitor-visibility-matrix",
    ),
    path(
        "runs/s/<str:slug>/answer-gap-faq/",
        AnswerGapFaqView.as_view(),
        name="answer-gap-faq",
    ),
    # Sales outreach benchmark — public, no login (see views/outreach.py).
    path("outreach/", OutreachBenchmarkCreateView.as_view(), name="outreach-create"),
    path("outreach/<str:slug>/", OutreachBenchmarkDetailView.as_view(), name="outreach-detail"),
    path("crawler/ingest/", CrawlerIngestView.as_view(), name="crawler-ingest"),
    path("runs/s/<str:slug>/crawler-logs/", CrawlerLogsView.as_view(), name="crawler-logs"),
    path("runs/s/<str:slug>/indexnow/", IndexNowView.as_view(), name="indexnow"),
    path(
        "runs/s/<str:slug>/entity-resolution/",
        EntityResolutionView.as_view(),
        name="entity-resolution",
    ),
    path(
        "runs/s/<str:slug>/citation-gaps/",
        CitationGapsView.as_view(),
        name="citation-gaps",
    ),
    path(
        "runs/s/<str:slug>/prompt-coverage/",
        PromptCoverageView.as_view(),
        name="prompt-coverage",
    ),
    path(
        "runs/s/<str:slug>/prompts/<int:track_id>/answer-block/",
        PromptAnswerBlockView.as_view(),
        name="prompt-answer-block",
    ),
    path(
        "runs/s/<str:slug>/crawler-access/",
        CrawlerAccessView.as_view(),
        name="crawler-access",
    ),
    path("runs/s/<str:slug>/shopping/", ShoppingReadinessView.as_view(), name="shopping-readiness"),
    path("runs/s/<str:slug>/shopping/sync/", ShoppingSyncView.as_view(), name="shopping-sync"),
    path("runs/s/<str:slug>/top-sources/", TopSourcesView.as_view(), name="top-sources"),
    path("runs/s/<str:slug>/citation-trend/", CitationTrendView.as_view(), name="citation-trend"),
    path("runs/s/<str:slug>/citations/", CitationSourcesView.as_view(), name="citation-sources"),
    path(
        "runs/s/<str:slug>/ai-recommendation-summary/",
        AiRecommendationSummaryView.as_view(),
        name="ai-recommendation-summary",
    ),
    path("runs/s/<str:slug>/geo-improvements/", GeoImprovementsView.as_view(), name="geo-improvements"),
    path(
        "runs/s/<str:slug>/apply-geo-fixes/", ApplyGeoFixesAndReanalyzeView.as_view(), name="apply-geo-fixes"
    ),
    path("runs/s/<str:slug>/competitors/", CompetitorListCreateView.as_view(), name="competitor-list-create"),
    path(
        "runs/s/<str:slug>/competitors/<int:competitor_id>/",
        CompetitorDetailView.as_view(),
        name="competitor-detail",
    ),
    path("runs/s/<str:slug>/auto-fix/", AutoFixView.as_view(), name="auto-fix"),
    path("runs/s/<str:slug>/auto-fix/preview/", AutoFixPreviewView.as_view(), name="auto-fix-preview"),
    path("runs/s/<str:slug>/auto-fix/approve/", AutoFixApproveView.as_view(), name="auto-fix-approve"),
    path("runs/s/<str:slug>/auto-fix/verify/", AutoFixVerifyView.as_view(), name="auto-fix-verify"),
    path("runs/s/<str:slug>/chat/", AiChatView.as_view(), name="ai-chat"),
    path(
        "runs/s/<str:slug>/domain-analytics/",
        DomainAnalyticsView.as_view(),
        name="domain-analytics",
    ),
    path(
        "runs/s/<str:slug>/domain-authority/",
        BrandDomainAuthorityView.as_view(),
        name="domain-authority",
    ),
    path(
        "runs/s/<str:slug>/overview-insights/",
        OverviewInsightsView.as_view(),
        name="overview-insights",
    ),
    # Blog composer (dashboard "Blog Agent" page)
    path("runs/s/<str:slug>/blog/posts/", BlogComposerPostsView.as_view(), name="blog-composer-posts"),
    path(
        "runs/s/<str:slug>/blog/posts/<int:post_id>/",
        BlogComposerPostsView.as_view(),
        name="blog-composer-post-delete",
    ),
    path(
        "runs/s/<str:slug>/blog/generate/",
        BlogComposerGenerateView.as_view(),
        name="blog-composer-generate",
    ),
    path(
        "runs/s/<str:slug>/blog/topics/",
        BlogComposerTopicsView.as_view(),
        name="blog-composer-topics",
    ),
    path(
        "runs/s/<str:slug>/blog/publish/",
        BlogComposerPublishView.as_view(),
        name="blog-composer-publish",
    ),
    path(
        "runs/s/<str:slug>/blog/upload-image/",
        BlogComposerUploadImageView.as_view(),
        name="blog-composer-upload-image",
    ),
    # Sitemap audit + AI agent log stub
    path("runs/s/<str:slug>/sitemap/", SitemapAuditDetailView.as_view(), name="sitemap-audit-detail"),
    path("runs/s/<str:slug>/sitemap/start/", SitemapAuditStartView.as_view(), name="sitemap-audit-start"),
    path("runs/s/<str:slug>/agent-log/", AgentLogView.as_view(), name="agent-log"),
    # Growth Agent — today's ranked task plan (ownership-checked, not AllowAny)
    path("runs/s/<str:slug>/agent/plan/", AgentPlanView.as_view(), name="agent-plan"),
    path(
        "runs/s/<str:slug>/agent/plan/refresh/",
        AgentPlanRefreshView.as_view(),
        name="agent-plan-refresh",
    ),
    # Schema watchtower
    path("runs/s/<str:slug>/schema-watch/", SchemaWatchDetailView.as_view(), name="schema-watch-detail"),
    path("runs/s/<str:slug>/schema-watch/start/", SchemaWatchStartView.as_view(), name="schema-watch-start"),
    # Rank tracker
    path("runs/s/<str:slug>/rank/", RankAuditDetailView.as_view(), name="rank-audit-detail"),
    path("runs/s/<str:slug>/rank/start/", RankAuditStartView.as_view(), name="rank-audit-start"),
    path(
        "runs/s/<str:slug>/rank/query/<int:query_id>/refresh/",
        RankAuditRefreshQueryView.as_view(),
        name="rank-audit-refresh-query",
    ),
    path("runs/s/<str:slug>/prompts/<int:track_id>/rank/", PromptRankView.as_view(), name="prompt-rank"),
    # Backlink marketplace
    path("runs/s/<str:slug>/backlinks/free/", RunBacklinkFreeView.as_view(), name="backlink-free"),
    path("runs/s/<str:slug>/backlinks/our/", OurBacklinksView.as_view(), name="backlink-our"),
    path(
        "runs/s/<str:slug>/backlinks/schedule/",
        BacklinkScheduleView.as_view(),
        name="backlink-schedule",
    ),
    # Public blog feed for the satellite sites (read-only, no auth; proxies S3).
    path("public/blog/<str:site>/", PublicBlogListView.as_view(), name="public-blog-list"),
    path(
        "public/blog/<str:site>/<str:post_slug>/",
        PublicBlogDetailView.as_view(),
        name="public-blog-detail",
    ),
    path(
        "runs/s/<str:slug>/blog/generate/",
        BlogGenerateView.as_view(),
        name="blog-generate",
    ),
    path(
        "runs/s/<str:slug>/blog/auto-publish-all/",
        BlogAutoPublishAllView.as_view(),
        name="blog-auto-publish-all",
    ),
    path(
        "runs/s/<str:slug>/blog/item/<str:site>/<str:post_slug>/",
        BlogPostDetailView.as_view(),
        name="blog-post-detail",
    ),
    path(
        "runs/s/<str:slug>/blog/sources/",
        BlogSourcesView.as_view(),
        name="blog-sources",
    ),
    path(
        "runs/s/<str:slug>/blog/title-ideas/",
        BlogTitleIdeasView.as_view(),
        name="blog-title-ideas",
    ),
    path(
        "runs/s/<str:slug>/blog/publish-network/",
        BlogPublishNetworkView.as_view(),
        name="blog-publish-network",
    ),
    path("runs/s/<str:slug>/backlinks/catalog/", BacklinkCatalogView.as_view(), name="backlink-catalog"),
    path(
        "runs/s/<str:slug>/backlinks/orders/", BacklinkOrderListCreateView.as_view(), name="backlink-orders"
    ),
    path(
        "runs/s/<str:slug>/backlinks/orders/<int:order_id>/",
        BacklinkOrderDetailView.as_view(),
        name="backlink-order-detail",
    ),
    path(
        "runs/s/<str:slug>/backlinks/orders/<int:order_id>/confirm-payment/",
        BacklinkOrderConfirmPaymentView.as_view(),
        name="backlink-order-confirm-payment",
    ),
    path(
        "runs/s/<str:slug>/prompts/<int:track_id>/wikipedia/draft/",
        PromptWikipediaDraftView.as_view(),
        name="prompt-wikipedia-draft",
    ),
    path(
        "runs/s/<str:slug>/prompts/<int:track_id>/schema/", PromptSchemaView.as_view(), name="prompt-schema"
    ),
    # Content optimisation
    path("runs/s/<str:slug>/content/pages/", ContentPagesView.as_view(), name="content-pages"),
    path("runs/s/<str:slug>/content/page/", ContentPageFieldsView.as_view(), name="content-page-fields"),
    path(
        "runs/s/<str:slug>/content/suggestions/", ContentSuggestionsView.as_view(), name="content-suggestions"
    ),
    path(
        "runs/s/<str:slug>/content/suggestions/<int:suggestion_id>/dismiss/",
        ContentSuggestionDismissView.as_view(),
        name="content-suggestion-dismiss",
    ),
    path("runs/s/<str:slug>/content/save/", ContentSaveView.as_view(), name="content-save"),
    path(
        "runs/s/<str:slug>/content/rewrite-element/",
        ContentRewriteElementView.as_view(),
        name="content-rewrite-element",
    ),
    path(
        "runs/s/<str:slug>/content/apply-element/",
        ContentApplyElementView.as_view(),
        name="content-apply-element",
    ),
    path(
        "runs/s/<str:slug>/content/raw-files/",
        ContentRawFilesListView.as_view(),
        name="content-raw-files-list",
    ),
    path(
        "runs/s/<str:slug>/content/raw-files/<str:name>/",
        ContentRawFileUpsertView.as_view(),
        name="content-raw-files-upsert",
    ),
    path("runs/s/<str:slug>/", AnalysisRunBySlugView.as_view(), name="run-by-slug"),
    path("runs/<int:run_id>/status/", AnalysisRunStatusView.as_view(), name="run-status"),
    path("runs/<int:run_id>/export-pdf/", ExportPDFView.as_view(), name="export-pdf"),
    # Gamification endpoints
    path("gamification/", UserGamificationView.as_view(), name="gamification"),
    path("gamification/stats/", ActionStatsView.as_view(), name="action-stats"),
    path("achievements/", AchievementsView.as_view(), name="achievements"),
    path("action-templates/", ActionTemplatesView.as_view(), name="action-templates"),
    # Action endpoints
    path("actions/", UserActionListView.as_view(), name="action-list"),
    path("actions/create/", CreateUserActionView.as_view(), name="action-create"),
    path("actions/sync/", SyncActionsView.as_view(), name="action-sync"),
    path("actions/<int:action_id>/assign/", AssignActionView.as_view(), name="action-assign"),
    path("actions/<int:action_id>/verify/", VerifyActionView.as_view(), name="action-verify"),
    path("actions/<int:action_id>/", UpdateUserActionView.as_view(), name="action-update"),
    path("actions/crawl-essentials/", CrawlEssentialsStatusView.as_view(), name="crawl-essentials"),
    path(
        "actions/blog-automation/config/", BlogAutomationConfigView.as_view(), name="blog-automation-config"
    ),
    path(
        "actions/blog-automation/calendar/",
        BlogAutomationCalendarView.as_view(),
        name="blog-automation-calendar",
    ),
    path(
        "actions/blog-automation/process-due/",
        BlogAutomationProcessDueView.as_view(),
        name="blog-automation-process-due",
    ),
    path(
        "actions/blog-automation/generate/",
        BlogAutomationGenerateView.as_view(),
        name="blog-automation-generate",
    ),
    path(
        "actions/blog-automation/publish/",
        BlogAutomationPublishView.as_view(),
        name="blog-automation-publish",
    ),
    path("actions/quick/", QuickActionView.as_view(), name="quick-action"),
    path("actions/bulk-create/", BulkCreateUserActionView.as_view(), name="bulk-create-action"),
    # Weekly email test
    path("runs/s/<str:slug>/email/weekly-test/", WeeklyTestEmailView.as_view(), name="weekly-test-email"),
]
