# Generated by Django 5.2.11 on 2026-08-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0068_analysisrun_outreach_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompttrack',
            name='search_volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompttrack',
            name='search_volume_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
