# Generated by Django 5.2.11 on 2026-08-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_agent', '0005_alter_githubfixjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubfixjob',
            name='recommendation_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
